language: cpp
sudo: required

before_install:
  - chmod +x install-ubuntu.sh
  - sudo apt-get -qq update
  - apt-cache search libuv
  - sudo apt-get install -y libuv-dev

install: ./install-ubuntu.sh

script: ./build.sh
